name: url_launcher_aurora
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher_platform_interface: ^2.2.0

flutter:
  plugin:
    implements: url_launcher
    platforms:
      aurora:
        pluginClass: UrlLauncherAuroraPlugin
        dartPluginClass: UrlLauncherAurora